openapi: 3.1.0
info:
  version: 1.0.0
  title: TaxOA.com
  termsOfService: https://dev.turbowotc.com/tax5
  contact:
    email: contact@taxoa.com
    url: https://dev.turbowotc.com/tax5
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://dev.turbowotc.com/tax5/backEnd/assets/images/logo.jpg
  description: >
    This is a TaxOA API server.
tags:
  - name: Employee
    description: Send Employee Data to TaxOA.  
servers:
  - url: https://dev.turbowotc.com/tax5/api/v2
paths:
  /employees:
    $ref: paths/employees.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
